services:

  frontend-webpack:
    image: node:20-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: npm run dev:webpack

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    healthcheck:
      test: "/usr/bin/pg_isready --dbname=${POSTGRESQL_DATABASE} --username=${POSTGRESQL_USERNAME} || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend-migrations:
    build:
      context: ./migrations
    env_file:
        - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: ["up", "-env=default", "-config=./dbconfig.yaml"]
    restart: "no"

  gateway:
    image: ghcr.io/authara-org/authara-gateway:v1.2.1
    ports:
      - "3000:3000"
    environment:
      GATEWAY_BIND: :3000
      AUTHARA_UPSTREAM: authara:8080
      APP_UPSTREAM: testapp:8080
    depends_on:
      - authara
      - testapp

  authara:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
    env_file:
        - .env
    depends_on:
      backend-migrations:
        condition: service_completed_successfully

  testapp:
    build:
      context: ./integrations/testapp/
    environment:
      AUTHARA_AUDIENCE: app
      AUTHARA_BASE_URL: http://authara:8080
      AUTHARA_ISSUER: ${AUTHARA_ISSUER}
      AUTHARA_JWT_KEYS: ${AUTHARA_JWT_KEYS}
      AUTHARA_WEBHOOK_SECRET: ${AUTHARA_WEBHOOK_SECRET}
    volumes:
      - ./integrations/testapp:/app
    restart: unless-stopped

volumes:
  postgres-data:

