FROM golang:1.25-alpine

RUN go install github.com/a-h/templ/cmd/templ@v0.3.977
RUN go install github.com/bokwoon95/wgo@latest

WORKDIR /app

COPY . .

RUN go mod download

CMD ["wgo", "-file=.go", "-file=.templ", "-xfile=_templ.go", "--", "templ" ,"generate" ,"::", "go" ,"run" ,"./cmd/authara/main.go"]
